// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/index.tsx";
import * as $$0 from "./islands/About.tsx";
import * as $$1 from "./islands/Awards.tsx";
import * as $$2 from "./islands/Contact.tsx";
import * as $$3 from "./islands/Footer.tsx";
import * as $$4 from "./islands/Hero.tsx";
import * as $$5 from "./islands/Navbar.tsx";
import * as $$6 from "./islands/Projects.tsx";

const manifest = {
  routes: {
    "./routes/index.tsx": $0,
  },
  islands: {
    "./islands/About.tsx": $$0,
    "./islands/Awards.tsx": $$1,
    "./islands/Contact.tsx": $$2,
    "./islands/Footer.tsx": $$3,
    "./islands/Hero.tsx": $$4,
    "./islands/Navbar.tsx": $$5,
    "./islands/Projects.tsx": $$6,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
