export const phrases = [
  "TypeScript enthusiast",
  "Low level wizard",
  "C master",
  "Blogging machine",
  "Deno lover",
  "Full-stack ninja",
  "Vue enthusiast",
  "Ruby rockstar",
  "Docker master",
  "Kubernetes whisperer",
  "Serverless samurai",
  "DevOps ninja",
  "Test-driven development devotee",
  "Agile practitioner",
  "Embedded systems pro",
  "Python mastermind",
  "Scrum master",
  "Git wizard",
  "Ruby ninja",
  "GitHub addict",
  "Open source enthusiast",
  "Hackathon champion",
  "Tech community builder",
  "Pythonista",
  "Pythonic prodigy",
  "Rubyist extraordinaire",
  "Pythonic visionary",
  "Ruby magician",
  "Ruby maven",
  "Sass sorcerer",
  "DEADBEEF",
] as const;
